default: &default
  adapter: postgresql
  encoding: unicode
  username: user
  password: user
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: polyclinic_development

test:
  <<: *default
  database: polyclinic_test

# production:
#   <<: *default
#   database: project_production
#   username: username
#   password: <%= ENV['PROJECT_DATABASE_PASSWORD'] %>
